apiVersion: v1
kind: Service
metadata:
  namespace: arba
  name: postgres-service
  labels:
    app: jobvacancy
spec:
  selector:
   app: postgres
  ports:
  - protocol: TCP
    port: 5432
  type: ClusterIP