kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: arba
  name: postgres-pv-volume
  labels:
    type: local
    app: jobvacancy
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/pv0001"