kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: arba
  name: postgres-pv-claim
  labels:
    app: jobvacancy
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi